fullnameOverride: auth-service

args: ["npm", "run", "start:prod"]

extraEnvVars:
  - name: JWT_TOKEN_SECRET
    value: JWTMrJobhopSecretKey
  - name: JWT_TOKEN_EXPIRES
    value: "30"
  - name: AUTH_SERVICE_MONGODB_URL
    value: mongodb://main:StrongP%40ssword@mongodb-0-external.data.svc.cluster.local/main
  - name: AUTH_SERVICE_RABITMQ_URL
    value: amqp://jobhop_dev:h5x}N4p:FF8Q)+rj@rabbitmq.data.svc.cluster.local:5672
  - name: AUTH_SERVICE_RABITMQ_QUEUE
    value: auth_queue
  - name: ASSET_URL
    value: https://assets.jobhopin.com
  - name: DEFAULT_PAGE_SIZE
    value: "20"
  - name: MAILGUN_SECRET
    value: key-2cc558d3f69010c497adfead8955493e
  - name: MAILGUN_DOMAIN
    value: mg.jobhop.in

nodeAffinityPreset:
  type: "hard"

livenessProbe:
  path: /health

readinessProbe:
  path: /health

containerSecurityContext:
  enabled: false

podSecurityContext:
  enabled: false
