fullnameOverride: activity-service

args: ["npm", "run", "start:prod"]

extraEnvVars:
  - name: JWT_TOKEN_SECRET
    value: JWTMrJobhopSecretKey
  - name: JWT_TOKEN_EXPIRES
    value: "30"
  - name: ACTIVITY_SERVICE_MONGODB_URL
    value: mongodb://activity:StrongP%40ssword@mongodb-0-external.data.svc.cluster.local/activity
  - name: ACTIVITY_SERVICE_RABITMQ_URL
    value: amqp://jobhop_dev:h5x}N4p:FF8Q)+rj@rabbitmq.data.svc.cluster.local:5672
  - name: ACTIVITY_SERVICE_RABITMQ_QUEUE
    value: activity_queue
  - name: ASSET_URL
    value: https://assets.jobhopin.com
  - name: DEFAULT_PAGE_SIZE
    value: "20"

nodeAffinityPreset:
  type: "hard"

livenessProbe:
  path: /health

readinessProbe:
  path: /health

containerSecurityContext:
  enabled: false

podSecurityContext:
  enabled: false
