fullnameOverride: organization-service

args: ['npm', 'run', 'start:prod']

extraEnvVars:
  - name: JWT_TOKEN_SECRET
    value: JWTMrJobhopSecretKey
  - name: JWT_TOKEN_EXPIRES
    value: '30'
  - name: ORGANIZATION_SERVICE_MONGODB_URL
    value: mongodb+srv://organization:sKrErP8VIaXZa09Y@mongodb-jobhop-prod.xbpov.mongodb.net/organization
  - name: ORGANIZATION_SERVICE_RABITMQ_URL
    value: amqp://jobhop_prod:JgpagP89Qw7DaKai@rabbitmq.data.svc.cluster.local:5672
  - name: ORGANIZATION_SERVICE_RABITMQ_QUEUE
    value: organization_queue
  - name: REDIS_HOST
    value: redis-master.data.svc.cluster.local
  - name: REDIS_PASSWORD
    value: o133We4sZLZ2wgir
  - name: REDIS_PORT
    value: '6379'
  - name: REDIS_TIMEOUT
    value: '3600'      
  - name: REDIS_USETLS
    value: 'false'  
  - name: ASSET_URL
    value: https://assets.jobhopin.com
  - name: DEFAULT_PAGE_SIZE
    value: '20'

nodeAffinityPreset:
  type: "hard"

livenessProbe:
  path: /health

readinessProbe:
  path: /health

containerSecurityContext:
  enabled: false

podSecurityContext:
  enabled: false
